-- SQLite

UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br'
WHERE NAME == 'Carolina' AND EMAIL == 'carol@ig.com.br';

UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19'
WHERE NAME == 'Josefa';

UPDATE CARS SET YEAR == 2019
WHERE NAME == 'Fiat Cronos' AND YEAR == 2022;

DELETE FROM CARS WHERE NAME == 'Hyundai HB20 1.6';

ALTER TABLE EMPLOYEES RENAME PHONE TO PHONE_NUMBER;

SELECT * FROM EMPLOYEES;