-- SQLite

SELECT LOCATIONS.ID AS 'LOCATION ID',
       CUSTOMERS.NAME || ' ' || CUSTOMERS.LASTNAME AS 'CUSTOMER',
       CARS.NAME AS 'CAR',
       EMPLOYEES.NAME AS 'EMPLOYEE'
       FROM LOCATIONS
       JOIN CUSTOMERS ON (LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
       JOIN CARS ON (LOCATIONS.CAR_ID = CARS.ID)
       JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID);

SELECT COUNT(*) AS LOCATIONS_QUANTITY FROM LOCATIONS;

SELECT ID AS 'LOCATION ID',
MAX(TOTAL) AS LOCATIONS_TOTAL_MAX
FROM LOCATIONS;

SELECT * FROM LOCATIONS WHERE START_DATE BETWEEN '2022-05-20' AND '2022-12-25';