SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS
WHERE STATE == 'SP';

SELECT 
    NAME,
    YEAR,
    COLOR,
    KM,
    STATUS,
    CAR_BRAND.BRAND_NAME,
    CAR_MODEL.MODEL_NAME 
FROM CARS
JOIN CAR_BRAND ON CAR_BRAND.ID == CARS.BRAND_ID
JOIN CAR_MODEL ON CAR_MODEL.ID == CARS.MODEL_ID
WHERE STATUS == 'Liberado';

SELECT 
    NAME,
    YEAR,
    COLOR,
    KM,
    STATUS,
    CAR_BRAND.BRAND_NAME,
    CAR_MODEL.MODEL_NAME 
FROM CARS
JOIN CAR_BRAND ON CAR_BRAND.ID == CARS.BRAND_ID
JOIN CAR_MODEL ON CAR_MODEL.ID == CARS.MODEL_ID
WHERE YEAR == 2016;

SELECT 
    NAME,
    PHONE_NUMBER,
    CONTRACT_DATE,
    POSITIONS.DESCRIPTION
FROM EMPLOYEES
JOIN POSITIONS ON POSITIONS.ID == EMPLOYEES.POSITION_ID;

SELECT EMPLOYEES.NAME,
       COUNT(LOCATIONS.EMPLOYEE_ID) AS LOCATIONS_QUANTITY
       FROM LOCATIONS
       LEFT JOIN EMPLOYEES ON LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID
       GROUP BY EMPLOYEE_ID
       HAVING LOCATIONS_QUANTITY >= 2;

SELECT CUSTOMERS.NAME,
       COUNT(LOCATIONS.CUSTOMER_ID) AS LOCATIONS_QUANTITY
       FROM LOCATIONS
       LEFT JOIN CUSTOMERS ON LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID
       GROUP BY CUSTOMER_ID
       HAVING LOCATIONS_QUANTITY >= 2;

