-- SQLite

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CONTRACT_DATE TEXT NOT NULL,
    POSITION_ID INTEGER NOT NULL,
    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID)
    );