-- SQLite

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    BIRTH_DATE TEXT NOT NULL
);