-- SQLite

SELECT EMPLOYEES.NAME,
       COUNT(LOCATIONS.EMPLOYEE_ID) AS LOCATIONS_QUANTITY
       FROM LOCATIONS
       LEFT JOIN EMPLOYEES ON LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID
       GROUP BY EMPLOYEE_ID
       HAVING LOCATIONS_QUANTITY >= 2;

