-- SQLite

SELECT 
    NAME,
    YEAR,
    COLOR,
    KM,
    STATUS,
    CAR_BRAND.BRAND_NAME,
    CAR_MODEL.MODEL_NAME 
FROM CARS
JOIN CAR_BRAND ON CAR_BRAND.ID == CARS.BRAND_ID
JOIN CAR_MODEL ON CAR_MODEL.ID == CARS.MODEL_ID
WHERE YEAR == 2016;